Added aliases and functions for git and vim

diff --git a/dot_files/dot_bashrc b/dot_files/dot_bashrc
--- a/dot_files/dot_bashrc
+++ b/dot_files/dot_bashrc
@@ -39,6 +39,11 @@ source ~/.git-completion.bash
 
 # bash Aliases
 alias ll='ls -la'
+alias mkdir="mkdir -p"
+# less interprets color escape sequences instead of
+# just printing them to the screen
+alias less="less -R"
+
 
 # vim Aliases
 alias bashrc="vim $HOME/.bashrc; if [ -f $HOME/.bash_profile ] ; then . $HOME/.bash_profile ; echo 'Sourced .bash_profile' ; else . $HOME/.bashrc ; echo 'Sourced .bashrc' ; fi"
@@ -46,6 +51,7 @@ alias bashaliases="vim $HOME/.bash_aliases; . $HOME/.bash_aliasees ; echo 'Sourc
 alias vimrc="vim $HOME/.vimrc"
 alias gitconfig="vim $HOME/.gitconfig"
 alias vimproj="echo $(git rev-parse --show-toplevel); vim  $(git rev-parse --show-toplevel)/*.xcodeproj/project.pbxproj"
+alias vim='vim -p ' # make sure vim opens up tabs for multiple files
 
 # git Aliases
 alias ga='git add'
@@ -55,7 +61,7 @@ alias gaproj='git aproj'
 alias gb='git branch'
 alias gc='git commit'
 alias gca='git commit --amend'
-alias gcm='git cm'
+#alias gcm='git cm' # Rewritten as function
 alias gco='git checkout'
 alias gcp='git cherry-pick'
 alias gd='git diff'
@@ -73,7 +79,7 @@ alias grbi='git rebase -i'
 alias grbo='git rebase --onto'
 alias grhe='git reset HEAD'
 alias grha='git reset --hard'
-alias gst='git stash'
+#alias gst='git stash' # Rewritten as function
 
 # gitk Aliases
 alias gitk='gitk 2>/dev/null &'
@@ -84,3 +90,106 @@ alias screen='screen -R'
 # puppie Aliases
 alias pshow='LC_ALL=C gpg -d ~/cute_puppies/cute_puppies.gpg'
 alias pedit='LC_ALL=C ~/docs/vigpg ~/cute_puppies/cute_puppies.gpg'
+
+# git helper functions
+
+function glga ()
+{
+	ssh-gas -q ; git log --show-signature --graph --decorate --color --all "$@" | less -R
+}
+
+function glg ()
+{
+	ssh-gas -q ; git log --show-signature --graph --decorate --color "$@" | less -R
+}
+
+function gcam ()
+{
+	ssh-gas -q ; git commit -a -m "$*"
+}
+
+function gcAm ()
+{
+	ssh-gas -q ; git add -A ; git commit -m "$*"
+}
+
+function gcmp ()
+{
+	ssh-gas -q ; git commit -m "$*" ; git push
+}
+
+function gcamp ()
+{
+	ssh-gas -q ; git commit -a -m "$*" ; git push
+}
+
+function gcAmp ()
+{
+	ssh-gas -q ; git add -A ; git commit -m "$*" ; git push
+}
+
+function gst ()
+{
+	ssh-gas -q
+
+	# run git status
+	git status
+
+	# See if there are any uninitialized submodules.
+	git submodule status | cut -c1 | grep -- '-' &> /dev/null
+	local ret="$?"
+
+	if [ "$ret" = 0 ] ; then
+		echo
+		echo "Uninitialized submodules.  Run \`git submodule update --init\`"
+	fi
+}
+
+# SSH Get Auth Sock.
+# This is a command to automatically update the SSH_AUTH_SOCK env var.
+# If "-q" is passed, then nothing will be output on error.
+# If "-v" is passed, then the auth sock that is currently being used
+# will be output.
+# (This is needed when connecting to a previously running
+# screen session, since the SSH_AUTH_SOCK variable will be the
+# previous one we were using.  We need a new updated one
+# for this new connection.)
+function ssh-gas ()
+{
+	local QUIET=""
+	local VERBOSE=""
+
+	for arg in "$@" ; do
+		if [[ "$arg" == '-h' || "$arg" == "--help" ]] ; then
+			echo "Usage: ${FUNCNAME[0]} [-h] [-v]"
+			echo "Set SSH_AUTH_SOCK environment variable."
+			return
+		elif [[ "$arg" == '-v' || "$arg" == "--verbose" ]] ; then
+			VERBOSE=1
+		elif [[ "$arg" == '-q' || "$arg" == "--quiet" ]] ; then
+			QUIET=1
+		else
+			die "Unknown argument \"${arg}\""
+		fi
+	done
+
+	# get all the existing agent files
+	shopt -q extglob
+	local SHOPT_PREV_VAL="$?"
+	shopt -s extglob
+	local agent_files="$(ls -rt /tmp/ssh-+([A-Za-z0-9 ])/agent.+([0-9]) 2>/dev/null)"
+	if  [ "$SHOPT_PREV_VAL" -eq "1" ] ; then
+		shopt -u extglob
+	fi
+
+	# make sure there actually are auth socks to get
+	if [ -z "$agent_files" ] ; then
+		[ ! "$QUIET" ] && echo "ERROR: no auth sock available"
+		return
+	fi
+
+	# get the most recently added ssh auth sock
+	local auth_sock="$(echo "$agent_files" | tail -1)"
+	[ "$VERBOSE" ] && echo "using auth sock: $auth_sock"
+	export SSH_AUTH_SOCK="$auth_sock"
+}
